openapi: 3.2.0
info:
  title: Pedtools Cop API
  version: 0.1.0
servers:
- url: /pedtools/v1
tags:
- name: Co P
paths:
  /cop/matrix:
    post:
      summary: Get Cop Matrix
      description: Get Coefficient of Parentage Matrix
      operationId: get_cop_matrix_cop_matrix_post
      parameters:
      - name: max_depth
        in: query
        required: false
        schema:
          anyOf:
          - type: integer
          - type: 'null'
          default: 10
          title: Max Depth
      - name: apikey
        in: header
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          title: apikey
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: string
              minItems: 1
              description: A list of variety names
              title: Preferred Names
            example:
            - TURKEY GID:10509
            - SANDPIPER
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                anyOf:
                - $ref: '#/components/schemas/COPResponse'
                - type: 'null'
                title: Response Get Cop Matrix Cop Matrix Post
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      tags:
      - Co P
components:
  schemas:
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    COPResponse:
      properties:
        reverse_mapping:
          additionalProperties:
            type: string
          type: object
          title: Reverse Mapping
        forward_mapping:
          additionalProperties:
            items:
              type: string
            type: array
          type: object
          title: Forward Mapping
        cop:
          additionalProperties:
            additionalProperties:
              type: number
            type: object
          type: object
          title: Cop
      type: object
      required:
      - reverse_mapping
      - forward_mapping
      - cop
      title: COPResponse
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
