openapi: 3.2.0
info:
  title: Pedtools API
  version: 0.1.0
servers:
- url: /pedtools/v1
tags:
- name: Pedtools
paths:
  /{variety}:
    get:
      summary: Varieties
      description: Get Matching Varieties
      operationId: varieties__variety__get
      parameters:
      - name: variety
        in: path
        required: true
        schema:
          type: string
          title: Variety
      - name: pedigree_depth
        in: query
        required: false
        schema:
          anyOf:
          - type: integer
          - type: 'null'
          default: 5
          title: Pedigree Depth
      - name: apikey
        in: header
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          title: apikey
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/VarietyModel'
                title: Response Varieties  Variety  Get
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      tags:
      - Pedtools
components:
  schemas:
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
    AliasBaseModel:
      properties:
        name:
          type: string
          title: Name
        type:
          anyOf:
          - type: string
          - type: 'null'
          title: Type
      type: object
      required:
      - name
      - type
      title: AliasBaseModel
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    VarietyBaseModel:
      properties:
        preferred_name:
          type: string
          title: Preferred Name
        crop_name:
          type: string
          title: Crop Name
        backcross_str:
          anyOf:
          - type: string
          - type: 'null'
          title: Backcross Str
        selfing_count:
          type: integer
          title: Selfing Count
        market_class:
          anyOf:
          - type: string
          - type: 'null'
          title: Market Class
        release_date:
          anyOf:
          - type: integer
          - type: 'null'
          title: Release Date
        developer:
          anyOf:
          - type: string
          - type: 'null'
          title: Developer
        parentage:
          anyOf:
          - type: string
          - type: 'null'
          title: Parentage
        aliases:
          items:
            $ref: '#/components/schemas/AliasBaseModel'
          type: array
          title: Aliases
      type: object
      required:
      - preferred_name
      - crop_name
      - backcross_str
      - selfing_count
      - market_class
      - release_date
      - developer
      - parentage
      - aliases
      title: VarietyBaseModel
    VarietyModel:
      properties:
        preferred_name:
          type: string
          title: Preferred Name
        crop_name:
          type: string
          title: Crop Name
        backcross_str:
          anyOf:
          - type: string
          - type: 'null'
          title: Backcross Str
        selfing_count:
          type: integer
          title: Selfing Count
        market_class:
          anyOf:
          - type: string
          - type: 'null'
          title: Market Class
        release_date:
          anyOf:
          - type: integer
          - type: 'null'
          title: Release Date
        developer:
          anyOf:
          - type: string
          - type: 'null'
          title: Developer
        parentage:
          anyOf:
          - type: string
          - type: 'null'
          title: Parentage
        aliases:
          items:
            $ref: '#/components/schemas/AliasBaseModel'
          type: array
          title: Aliases
        mother:
          anyOf:
          - $ref: '#/components/schemas/VarietyBaseModel'
          - type: 'null'
        father:
          anyOf:
          - $ref: '#/components/schemas/VarietyBaseModel'
          - type: 'null'
        pedigree:
          anyOf:
          - type: string
          - type: 'null'
          title: Pedigree
      type: object
      required:
      - preferred_name
      - crop_name
      - backcross_str
      - selfing_count
      - market_class
      - release_date
      - developer
      - parentage
      - aliases
      - pedigree
      title: VarietyModel
